version: '3.4'

services:

  pg:
    image: postgres
    container_name: postgres
    command: postgres -c 'max_connections=400'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: playground
    ports:
      - "5433:5432"
    networks:
      - testtasknetwork

  test-task:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: test-task
    ports:
      - 8075:8075
      - 18075:18075
    depends_on:
      - pg
    environment:
      SPRING_PROFILES_ACTIVE: demo
    networks:
      - testtasknetwork
networks:
  testtasknetwork:
    driver: bridge
